In [ ]:
5

In [ ]:
0

b)

In [1]:
a=[]
for i in range(1,11):
    if i==5:
        a.append(1)
    else:
        a.append(0)
print(a)

[0, 0, 0, 0, 1, 0, 0, 0, 0, 0]


In [2]:
a=[*range(10,50,1)]
print(a)

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]


In [3]:
a=[1,2,3,4]
a[::-1]

[4, 3, 2, 1]

In [4]:
import numpy as np
a=np.array([[0,1,2],[3,4,5],[6,7,8]])
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [6]:
import numpy as np
a=np.random.random((10,10))
print(a)

[[3.20225056e-01 1.94363026e-01 5.69851779e-02 7.07364336e-01
  5.39102678e-01 3.66164694e-01 9.37177520e-01 5.58093486e-01
  4.27615306e-01 2.37199982e-01]
 [5.85996445e-01 8.43493043e-01 4.25629107e-01 9.38214056e-02
  5.14801837e-02 8.03033959e-01 7.01822465e-01 2.74219489e-01
  8.88816646e-01 5.61943683e-01]
 [6.24548012e-01 8.56234943e-01 9.39817376e-01 4.18605981e-01
  2.77845517e-02 8.37280400e-01 4.68288737e-01 7.96582889e-01
  3.60324679e-01 1.78610646e-02]
 [8.30495566e-01 4.11816459e-01 1.61194426e-01 8.06501953e-01
  6.56458316e-01 2.51966338e-01 1.42949861e-02 1.69771945e-02
  1.74161361e-02 9.61517738e-01]
 [2.30050031e-01 6.67482052e-01 7.11975806e-01 5.52490999e-01
  8.00467979e-01 8.46234575e-02 2.04348160e-02 6.12083173e-02
  2.08513166e-02 2.66451229e-01]
 [3.03330993e-01 9.13019999e-01 7.04541602e-01 8.16507571e-01
  1.68244105e-02 2.69116766e-01 4.64084407e-01 8.00917136e-05
  8.94203175e-01 9.39045140e-01]
 [2.96894594e-01 7.79571065e-01 7.07802505e-01 5.74173267e

In [7]:
a.max()

0.9615177379789889

In [8]:
a.min()

8.00917136091206e-05

In [4]:
a= 'i.love.programming.language'
b= a.split('.')
b[::-1]

['language', 'programming', 'love', 'i']

In [5]:
import pandas as pd
ind=['row 1', 'row 2','row 3', 'row 4','row 5', 'row 6']
col=['col 1', 'col 2','col 3', 'col 4', 'col 5', 'col 6']
pd.DataFrame({'index':ind,'column1':col,'column2':col,'column3':col,'column4':col,'column5':col})

index column1 column2 column3 column4 column5
0  row 1   col 1   col 1   col 1   col 1   col 1
1  row 2   col 2   col 2   col 2   col 2   col 2
2  row 3   col 3   col 3   col 3   col 3   col 3
3  row 4   col 4   col 4   col 4   col 4   col 4
4  row 5   col 5   col 5   col 5   col 5   col 5
5  row 6   col 6   col 6   col 6   col 6   col 6

In [6]:
x=15
def mul(x):
    return(x)
print('Double the number of=',x,mul(x*2))
print('trible the number of=',x,mul(x*3))
print('quadruple the number of=',x,mul(x*4))
print('quintuple the number of=',x,mul(x*5))

Double the number of= 15 30
trible the number of= 15 45
quadruple the number of= 15 60
quintuple the number of= 15 75


In [7]:
x= lambda s :True if s[0]=='h'  else False
print(x('hello'))

True


In [8]:
a,b=23,45
print("before swapping a:",a,"b:",b)
a,b=b,a
print("after swapping a:",a,"b:",b)

before swapping a: 23 b: 45
after swapping a: 45 b: 23


In [9]:
n=int(input("enter a number:"))
t=n
s=0
while n>0:
    r=n%10
    s=s*10+r
    n=n//10
if t==s :
    print(t," is a palindrome")
else:
    print(t," is not a palindrome")

enter a number:12
12  is not a palindrome


In [11]:
n=int(input("enter a number:"))
l=[]
for i in range(2,n):
    if n%i==0:
        l.append(i)
l[0]

enter a number:15


3

In [12]:
num =int(input("enter a number:"))
if num > 1:
    for i in range(2,num):
        if (num % i) == 0:
            print(num,"is not a prime number")
            break
        else:
            print(num,"is a prime number")
            break
else:
    print(num,"is not a prime number")

enter a number:3
3 is a prime number


In [13]:
s='1a2b3c4d5e'
d=[]
a=[]
for i in s:
    if i.isdigit()==True:
        d.append(i)
    else:
        a.append(i)
print(d)
print(a)

['1', '2', '3', '4', '5']
['a', 'b', 'c', 'd', 'e']


In [14]:
n=int(input("enter a number:"))
t=n
s=0
for i in range(1,n):
    if n%i==0:
        s=s+i
if t==s :
    print(t," is a perfect number")
else:
    print(t," is not a perfect number")

enter a number:6
6  is a perfect number


In [16]:
n=int(input("enter a number:"))
t=n
s=0
while n>0:
    r=n%10
    s=s+(r**3)
    n=n//10
if t==s :
    print(t," is a armstrong number")
else:
    print(t," is not a armstrong number")

enter a number:444
444  is not a armstrong number


In [17]:
n=int(input("enter a number:"))
t=n
s=0
while n>0:
    fa=1
    r=n%10
    for i in range(1,r+1):
        fa=fa*i
    s=s+fa
    n=n//10
if t==s :
    print(t," is a strong number")
else:
    print(t," is not a strong number")

enter a number:333
333  is not a strong number


In [18]:
import numpy as np
a=np.arange(10)
s=0
for i in a:
    s=s+i
print(a)
print("sum:",s)

[0 1 2 3 4 5 6 7 8 9]
sum: 45


In [19]:
for i in range(15,50):
    if i%5==0 and i%3==0:
        print(i)

15
30
45


In [20]:
x=2
a=range(1,11)
for i in a:
    print(x,'*',i,'=',i+i)

2 * 1 = 2
2 * 2 = 4
2 * 3 = 6
2 * 4 = 8
2 * 5 = 10
2 * 6 = 12
2 * 7 = 14
2 * 8 = 16
2 * 9 = 18
2 * 10 = 20


In [21]:
for i in range(1,101):
    if i==56:
        continue
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100


In [22]:
n=int(input("enter a number:"))
if n%2!=0:
    print("its weird")
    print("its odd")
elif 2<=n<=5:
    print("its  not weird")
    print("lies between 2 to 5")
elif 6<=n<=20:
    print("its  weird")
    print("lies between 6 to 20")
else:
    print("its  not weird")
    print("its greater than 20")

enter a number:78
its  not weird
its greater than 20
